name: Manual Docker Build - GHCR

on:
  workflow_dispatch:
    inputs:
      BASE_IMAGE:
        description: "Base image"
        required: true
        default: "nvidia/cuda:12.4.1-runtime-ubuntu22.04"
      COMFYUI_VERSION:
        description: "ComfyUI version"
        required: true
        default: "v0.3.15"
      PYTHON_VERSION:
        description: "Python version"
        required: true
        default: "3.12"
      TORCH_VERSION:
        description: "PyTorch version"
        required: true
        default: "2.6.0"
      CUDA_VERSION:
        description: "CUDA version"
        required: true
        default: "cu124"
      EXTRA_TAG:
        description: "Extra tag"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=comfyui:${{ github.event.inputs.COMFYUI_VERSION }}-torch${{ github.event.inputs.TORCH_VERSION }}-${{ github.event.inputs.CUDA_VERSION }}${{ github.event.inputs.EXTRA_TAG }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --build-arg BASE_IMAGE=${{ github.event.inputs.BASE_IMAGE }} \
            --build-arg COMFYUI_VERSION=${{ github.event.inputs.COMFYUI_VERSION }} \
            --build-arg PYTHON_VERSION=${{ github.event.inputs.PYTHON_VERSION }} \
            --build-arg TORCH_VERSION=${{ github.event.inputs.TORCH_VERSION }} \
            --build-arg CUDA_VERSION=${{ github.event.inputs.CUDA_VERSION }} \
            -t ghcr.io/${{ env.OWNER_LC }}/$IMAGE_TAG .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.OWNER_LC }}/$IMAGE_TAG
